### ISSUE TITLE
Feature deprecations in Chrome

### ISSUE THREAD

**Issue by tomayac** [gironajs/trobades#5]
**Títol de la xerrada**
Feature deprecations in Chrome

**Descripció**
We often talk about new features that land in browsers and how exciting they are. This talk, though, focuses on _deprecating_ features from one of the major browsers, namely Chrome, and details some of the steps the Chrome team takes to make sure the impact is as low as possible. There will be zombies…

**Duració**
Llarga (>30min).

**Idioma**
Català (best effort, slides in English)

**Temes tractats**
- Web compatibility

**Presentadors**
- Thomas Steiner &rarr; [Mastodon](https://toot.cafe/@tomayac)

**Altres notes**
Full disclosure: I work on the Chrome team at Google.

**Comment by llorenspujol** [comment]
DONE! 👏  

 [slides](https://goo.gle/chrome-deprecations)

![image](https://github.com/gironajs/trobades/assets/18361241/9f44b073-a460-4b41-b21e-90da4e6f8234)
