### ISSUE TITLE
Millorem Agile, que son els PIs i com us poden ajudar

### ISSUE THREAD

**Issue by jmar5439** [gironajs/trobades#9]
**Títol de la xerrada**

de Product Management a Project Manager , que son els PIs i com poden millorar la colaboració entre equips i developers

**Descripció**
Que es un PI en el context agile.
Perquè serveix un PI
Com les grans empreses fan servir PIs per sincronizar equips.

**Duració**
Llarga

**Idioma**
Català

**Temes tractats**
-  Agile Frameworks

**Presentadors**
-  jordi marti
- http://linkedin.com/in/jordi-marti-carreras-13949323

**Altres notes**

**Comment by llorenspujol** [comment]
Merci per la proposta @jmar5439 !

Ara bé, crec que el tema s'allunya bastant del que interessa a la comunitat de GironaJS. De totes maneres, deixem passar un temps a veure si hi ha algun "upvote" 👍

Thanks!
